using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



namespace bio2_rndx
{

    // a static class to return all item based info
    public static class LIB_ITEM
    {
        
        /// <summary>
        /// ALL ITEMS
        /// </summary>
        public static Dictionary<byte, string> BIO2_ITEM_LUT = new Dictionary<byte, string>()
        {
            {0x00, "Nothing"},
            {0x01, "Knife"},
            {0x02, "H&K VP70"},
            {0x03, "Browning"},
            {0x04, "Custom Handgun" },
            {0x05, "Magnum"},
            {0x06, "Custom Magnum"},
            {0x07, "Shotgun" },
            {0x08, "Custom Shotgun" },
            {0x09, "G Launcher (G)" },
            {0x0A, "G Launcher (F)" },
            {0x0B, "G Launcher (A)" },
            {0x0C, "Bowgun" },
            {0x0D, "Colt S.A.A"},
            {0x0E, "Sparkshot" },
            {0x0F, "Ingram" },
            {0x10, "Flamethrower" },
            {0x11, "Rocket Launcher" },
            {0x12, "Gatling Gun"},
            {0x13, "Beretta M29FS" },
            {0x14, "Handgun Ammo" },
            {0x15, "Shotgun Ammo" },
            {0x16, "Magnum Ammo"},
            {0x17, "Flamer Fuel" },
            {0x18, "Grenade Rounds" },
            {0x19, "Flame Rounds" },
            {0x1A, "Acid Rounds" },
            {0x1B, "SMG ammo" },
            {0x1C, "Sparkshot ammo" },
            {0x1D, "Bowgun Ammo" },
            {0x1E, "Ink Ribbon" },
            {0x1F, "Small Key" },
            {0x20, "Handgun Parts" },
            {0x21, "Magnum Parts" },
            {0x22, "Shotgun Parts" },
            {0x23, "F-Aid Spray" },
            {0x24, "Antivirus Bomb" },
            {0x25, "Chemical ACw-32" },
            {0x26, "Green Herb" },
            {0x27, "Red Herb" },
            {0x28, "Blue Herb" },
            {0x29, "G + G Herb" },
            {0x2A, "G + R Herb" },
            {0x2B, "G + B Herb" },
            {0x2C, "G + G + G Herb" },
            {0x2D, "G + G + B Herb" },
            {0x2E, "G + R + B Herb" },
            {0x2F, "Lighter" },
            {0x30, "Lockpick" },
            {0x31, "Sherry Photo"},
            {0x32, "Valve Handle" },
            {0x33, "Red Jewel" },
            {0x34, "Red Card" },
            {0x35, "Blue Card" },
            {0x36, "Serpent Stone" },
            {0x37, "Jaguar Stone" },
            {0x38, "Jaguar Stone L" },
            {0x39, "Jaguar Stone R" },
            {0x3A, "Eagle Stone" },
            {0x3B, "Bishop Plug" },
            {0x3C, "Rook Plug" },
            {0x3D, "Knight Plug" },
            {0x3E, "King Plug" },
            {0x3F, "Weapon Storage key" },
            {0x40, "Detonator" },
            {0x41, "C4" },
            {0x42, "C4+ Detonator" },
            {0x43, "Crank" },
            {0x44, "Film A" },
            {0x45, "Film B" },
            {0x46, "Film C" },
            {0x47, "Unicorn Medal" },
            {0x48, "Eagle Medal" },
            {0x49, "Wolf Medal" },
            {0x4A, "Cog" },
            {0x4B, "Manhole opener" },
            {0x4C, "Main Fuse" },
            {0x4D, "Fuse Case" },
            {0x4E, "Vaccine" },
            {0x4F, "Vaccine Container" },
            {0x50, "Film D" },
            {0x51, "Base Vaccine" },
            {0x52, "G-Virus" },
            {0x53, "Special Key" },
            {0x54, "Joint S Plug" },
            {0x55, "Joint N Plug" },
            {0x56, "Wire" },
            {0x57, "Ada's Photo" },
            {0x58, "Cabin Key" },
            {0x59, "Spade Key" },
            {0x5A, "Diamond Key" },
            {0x5B, "Heart Key" },
            {0x5C, "Club Key" },
            {0x5D, "Control Pannel Key (Down)" },
            {0x5E, "Control Pannel Key (Up)" },
            {0x5F, "Power Room Key" },
            {0x60, "MO Disk" },
            {0x61, "Umbrella KeyCard" },
            {0x62, "Master Key" },
            {0x63, "Platform Key"},
            {0x64, "Sparkshot Handle"},
            {0x65, "Ingram Stock"},
            {0x66, "Flamethrower Handle"},
            {0x67, "Rocket Launcher Base" },
            {0x68, "Chris's Diary" },
            {0x69, "Federal Police Report" },
            {0x6A, "MEMO TO LEON" },
            {0x6B, "Police memorandum" },
            {0x6C, "Operation Report" },

            {0x6D, "Mail to the chief"},
            {0x6E, "Mail to the chief" },
            {0x6F, "User Registration"},
            {0x70, "Secretary's Diary A" },
            {0x71, "Secretary's Diary B" },
            {0x72, "Operation Report 2" },
            {0x73, "Film A Picture" },
            {0x74, "Film B Picture" },
            {0x75, "Film C Picture" },
            {0x76, "Patrol Report" },
            {0x77, "Watchman's Diary" },
            {0x78, "Chiefs Diary" },
            {0x79, "Sewer Manager diary" },
            {0x7A, "Sewer manager Fax" },
            {0x7B, "Film D Picture" },
            {0x7C, "Vaccine synthesis (claire a)" },
            {0x7D, "Lab Security Manual" },

            {0x7E, "P-epsilon report" },
            {0x7F, "Hint files (Rookie file 1)" },
            {0x80, "Hint files (Rookie file 2)" },


        };

        // LEON A KEY TABLE
        public static Dictionary<byte, string> BIO2_KEY_LUT_LA = new Dictionary<byte, string>()
        {
            {0x24, "Lighter"},
            {0x32, "Valve Handle"},
            {0x33, "Red Jewel"},
            {0x34, "Red Card"},
            {0x35, "Blue Card"},
            {0x3B, "Bishop Plug"},
            {0x3C, "Rook Plug"},
            {0x3D, "Knight Plug"},
            {0x3E, "King Plug"},
            {0x3F, "Weapon Storage Key"},


            {0x43, "Crank"},
            {0x44, "Film A"},
            {0x45, "Film B"},
            {0x46, "Film C"},
            {0x47, "Unicorn Medal"},
            {0x48, "Eagle Medal"},
            {0x49, "Wolf Medal"},
            {0x4A, "Cog"},
            {0x4B, "Manhole Opener"},
            {0x4C, "Main Fuse"},
            {0x4D, "Fuse Case"},
            {0x50, "Film D"},
            {0x54, "Joint S Plug"},
            {0x55, "Joint N Plug"},
            {0x56, "Wire" },
            {0x53, "Special Key"},
            {0x59, "Spade Key"},
            {0x5A, "Diamond Key"},
            {0x5B, "Heart Key"},
            {0x5C, "Club Key" },
            {0x5D, "Control Panel Key(Down)" },
            {0x60, "MO DISK"},
            {0x61, "Umbrella Keycard"},
            {0x63, "Platform Key"},
            //{0x73, "Film A Picture" },
            //{0x74, "Film B Picture" },
            //{0x75, "Film C Picture" },
            //{0x7B, "Film D Picture" },


        };


        public static Dictionary<byte, string> BIO2_KEY_LUT_CA = new Dictionary<byte, string>()
        {
              {0x2F, "Lighter" },
            {0x30, "Lockpick" },
            {0x31, "Sherry Photo"},
            {0x32, "Valve Handle"},
            {0x33, "Red Jewel"},
            {0x34, "Red Card"},
            {0x35, "Blue Card"},
            {0x36, "Serpent Stone" },
            {0x37, "Jaguar Stone" },
            {0x38, "Jaguar Stone L" },
            {0x39, "Jaguar Stone R" },
            {0x3A, "Eagle Stone" },
            {0x3F, "Weapon Storage Key"},

              {0x40, "Detonator" },
            {0x41, "C4" },
            {0x42, "C4+ Detonator" },
            {0x43, "Crank"},
            {0x44, "Film A"},
            {0x45, "Film B"},
            {0x46, "Film C"},
            {0x47, "Unicorn Medal"},
            {0x48, "Eagle Medal"},
            {0x49, "Wolf Medal"},
            {0x4A, "Cog"},
            {0x4C, "Main Fuse"},
            {0x4D, "Fuse Case"},
            {0x50, "Film D"},
            {0x54, "Joint S Plug"},
            {0x55, "Joint N Plug"},
            {0x56, "Wire" },
            {0x53, "Special Key"},
            {0x59, "Spade Key"},
            {0x5A, "Diamond Key"},
            {0x5B, "Heart Key"},
            {0x5C, "Club Key" },
            {0x5D, "Control Panel Key(Down)" },
            {0x60, "MO DISK"},
            {0x61, "Umbrella Keycard"},
            {0x63, "Platform Key"},
            //{0x73, "Film A Picture" },
            //{0x74, "Film B Picture" },
            //{0x75, "Film C Picture" },
            //{0x7B, "Film D Picture" },


        };



        public static Dictionary<byte, string> BIO2_COMMON_LUT_LA = new Dictionary<byte, string>()
        {
            {0x00, "Nothing"},
            {0x02, "H&K VP70"},
            {0x04, "Custom Handgun" },
            {0x05, "Magnum"},
            {0x06, "Custom Magnum"},
            {0x07, "Shotgun" },
            {0x08, "Custom Shotgun" },
            {0x0F, "Ingram" },
            {0x10, "Flamethrower" },
            {0x11, "Rocket Launcher"},
            {0x14, "Handgun Ammo" },
            {0x15, "Shotgun Ammo" },
            {0x16, "Magnum Ammo"},
            {0x17, "Flamer Fuel" },
            {0x1B, "SMG ammo" },
            {0x1E, "Ink Ribbon" },
            {0x1F, "Small Key" },
            {0x20, "Handgun Parts" },
            {0x21, "Magnum Parts" },
            {0x22, "Shotgun Parts" },
            {0x23, "F-Aid Spray" },
            {0x26, "Green Herb" },
            {0x27, "Red Herb" },    
            {0x28, "Blue Herb" },

                {0x29, "G + G Herb" },
            {0x2A, "G + R Herb" },
            {0x2B, "G + B Herb" },
            {0x2C, "G + G + G Herb" },
            {0x2D, "G + G + B Herb" },
            {0x2E, "G + R + B Herb" },


        };

        public static Dictionary<byte, string> BIO2_COMMON_LUT_CA = new Dictionary<byte, string>()
        {
            {0x00, "Nothing"},                  
            {0x03, "Browning"},           
            {0x09, "G Launcher (G)" },
            {0x0A, "G Launcher (F)" },
            {0x0B, "G Launcher (A)" },
            {0x0C, "Bowgun" },
            {0x0D, "Colt S.A.A"},  
            {0x0F, "Ingram" },
            {0x10, "Flamethrower" },   
            {0x13, "Beretta M29FS" },
            {0x14, "Handgun Ammo" },        
            {0x17, "Flamer Fuel" },
            {0x18, "Grenade Rounds" },
            {0x19, "Flame Rounds" },
            {0x1A, "Acid Rounds" },
            {0x1B, "SMG ammo" },
            {0x1C, "Sparkshot ammo" },
            {0x1D, "Bowgun Ammo" },
            {0x1E, "Ink Ribbon" },
            {0x1F, "Small Key" },
            {0x20, "Handgun Parts" },
            {0x21, "Magnum Parts" },    
            {0x23, "F-Aid Spray" },
            {0x26, "Green Herb" },
            {0x27, "Red Herb" },
            {0x28, "Blue Herb" },   

        };


        // quantity of common items/weapons
        public static Dictionary<byte, byte> BIO2_LUT_QUANTITY = new Dictionary<byte, byte>
        {
            { 0x01, 0x01},
            { 0x02, 0x12},
            { 0x03, 0x0F},
            { 0x04, 0x0F},
            { 0x05, 0x07},
            { 0x06, 0x07},
            { 0x07, 0x05},
            { 0x08, 0x05 },
            { 0x09, 0x0A},
            { 0x0A, 0x0A },
            { 0x0B, 0x0A },
            { 0x0C, 0x1F },
            { 0x0D, 0x06},
            { 0x0E, 0x64},
            { 0x0F, 0x64},
            { 0x10, 0x64},
            { 0x11, 0x01 },
            { 0x12, 0x64},
            { 0x13, 0x0F},
            { 0x14, 0x0A},
            { 0x15, 0x05},
            { 0x16, 0x07},
            { 0x17, 0x64},
            { 0x18, 0x0A },
            { 0x19, 0x0A },
            { 0x1A, 0x0A},
            { 0x1B, 0x64},
            { 0x1C, 0x64},
            { 0x1D, 0x02},
            { 0x1E, 0x03 },
            { 0x1F, 0x03 },
            { 0x20, 0x01 },
            { 0x21, 0x01 },
            { 0x22, 0x01 },
            { 0x23, 0x01 },
            { 0x26, 0x01 },
            { 0x27,0x01 },
            { 0x28, 0x01 },

            
            {0x59, 0x02}, // spade
            {0x5A, 0x02}, // diamond
            {0x5B, 0x01}, // heart
            {0x5C, 0x03},// club


        };


        /// <summary>
        /// STRING > ID
        /// </summary>
        public static Dictionary<string, byte> BIO2_ITEM_LUT_INVERSE = new Dictionary<string, byte>()
        {
            {"Nothing", 0x00},
            {"Knife", 0x01},
            {"H&K VP70", 0x02},
            {"Browning", 0x03},
            {"Custom Handgun" ,0x04},
            {"Magnum", 0x05},
            {"Custom Magnum", 0x06},
            {"Shotgun", 0x07},
            {"Custom Shotgun",0x08},
            {"G Launcher (G)", 0x09},
            {"G Launcher (F)", 0x0A},
            {"G Launcher (A)" ,0x0B},
            {"Bowgun", 0x0C},
            {"Colt S.A.A", 0x0D},
            {"Sparkshot", 0x0E},
            {"Ingram" , 0x0F},
            {"Flamethrower" , 0x10},
            {"Rocket Launcher",0x11},
            {"Gatling Gun",0x12},
            {"Beretta M29FS",0x13},
            {"Handgun Ammo", 0x14},
            {"Shotgun Ammo",0x15},
            {"Magnum Ammo", 0x16},
            {"Flamer Fuel", 0x17},
            {"Grenade Rounds" , 0x18},
            {"Flame Rounds" ,0x19},
            {"Acid Rounds" ,0x1A},
            {"SMG ammo", 0x1B},
            {"Sparkshot ammo",0x1C},
            {"Bowgun Ammo",0x1D },
            {"Ink Ribbon", 0x1E},
            {"Small Key", 0x1F},
            {"Handgun Parts", 0x20},
            {"Magnum Parts", 0x21},
            {"Shotgun Parts", 0x22},
            {"F-Aid Spray", 0x23},
            {"Antivirus Bomb", 0x24},
            {"Chemical ACw-32", 0x25},
            {"Green Herb", 0x26},
            {"Red Herb", 0x27},
            {"Blue Herb", 0x28},
            {"G + G Herb", 0x29},
            {"G + R Herb", 0x2A},
            {"G + B Herb", 0x2B},
            {"G + G + G Herb", 0x2C},
            {"G + G + B Herb", 0x2D},
            {"G + R + B Herb", 0x2E},
            {"Lighter", 0x2F},
            {"Lockpick", 0x30},
            {"Sherry Photo", 0x31},
            {"Valve Handle", 0x32},
            {"Red Jewel", 0x33},
            {"Red Card", 0x34},
            {"Blue Card", 0x35},
            {"Serpent Stone", 0x36},
            {"Jaguar Stone", 0x37},
            {"Jaguar Stone L", 0x38},
            {"Jaguar Stone R", 0x39},
            {"Eagle Stone", 0x3A},
            {"Bishop Plug", 0x3B},
            {"Rook Plug", 0x3C},
            {"Knight Plug", 0x3D},
            {"King Plug", 0x3E},
            {"Weapon Storage key", 0x3F},
            {"Detonator", 0x40},
            {"C4" , 0x41},
            {"C4+ Detonator", 0x42},
            {"Crank", 0x43},
            {"Film A", 0x44},
            {"Film B", 0x45},
            {"Film C", 0x46},
            {"Unicorn Medal",0x47},
            {"Eagle Medal",0x48},
            {"Wolf Medal", 0x49},
            {"Cog", 0x4A},
            {"Manhole opener", 0x4B},
            {"Main Fuse", 0x4C},
            {"Fuse Case",0x4D},
            {"Vaccine" ,0x4E},
            {"Vaccine Container",0x4F},
            {"Film D", 0x50},
            {"Base Vaccine" ,0x51},
            {"G-Virus", 0x52},
            {"Base Vaccine (case only)", 0x53},
            {"Joint S Plug", 0x54},
            {"Joint N Plug", 0x55},
            {"Wire" , 0x56},
            {"Ada's Photo", 0x57},
            {"Cabin Key" , 0x58},
            {"Spade Key", 0x59},
            {"Diamond Key", 0x5A},
            {"Heart Key", 0x5B},
            {"Club Key", 0x5C},
            {"Control Pannel Key (Down)", 0x5D},
            {"Control Pannel Key (Up)", 0x5E},
            {"Power Room Key",0x5F},
            { "MO Disk",0x60},
            {"Umbrella KeyCard", 0x61},
            {"Master Key", 0x62},
            {"Platform Key",0x63},
            {"Sparkshot Handle", 0x64},
            {"Ingram Stock", 0x65},
            {"Flamethrower Handle", 0x66},
            {"Rocket Launcher Base", 0x67},
            {"Gatling Base", 0x68}
            
        };


        public static Dictionary<byte, string> BIO2_PUZZLE_LUT = new Dictionary<byte, string>()
        {
            {11, "Jewl Puzzle" },
            {13, "Gem Statue"},
            {17, "Library Puzzle"},
            {19, "Library Desk" },

            {30, "Unicorn Statue" },
            {33, "Waiting Room Desk"},

            {47, "Film A Return" },
            {48, "Film B Return" },
            {49, "Film C Return" },
            {50, "Film D Return" },
            {58, "Safe"},
            {59, "Torch Puzzle"},
            {71, "Weapon Cache" },
            {72, "Weapon Cache" },
            {73, "Weapon Cache" },
            {74, "Weapon Cache"},
            {140, "Weapon Cache"},
         


        };

        //public static Dictionary<byte, int> Location_SuitKey = new Dictionary<byte, int>()
        //{
        //    {0x59},
        //    {0x5A}

        //};


    }
}
